CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE TYPE publication_status AS ENUM ('DRAFT','PUBLISHED','ARCHIVED');
CREATE TYPE verification_status AS ENUM ('VERIFIED','DECLARED','UNKNOWN','EXPIRED');
CREATE TYPE source_authority AS ENUM ('OFFICIAL','LAND_OBSERVED','PARTNER','SELLER','THIRD_PARTY','LEGACY_IMPORT','UNKNOWN');
CREATE TYPE permission_status AS ENUM ('ALLOWED','DENIED','UNKNOWN');
CREATE TYPE location_role AS ENUM ('DECLARED','OBSERVED','VERIFIED');
CREATE TYPE release_status AS ENUM ('DRAFT','VALIDATED','APPROVED','REJECTED','PUBLISHED','RETIRED');
CREATE TYPE import_status AS ENUM ('UPLOADED','VALIDATING','READY_FOR_REVIEW','REJECTED','COMMITTED','FAILED');

CREATE TABLE product_identity (id boolean PRIMARY KEY DEFAULT true CHECK(id), product text NOT NULL CHECK(product='TAXUA_LAND'));
INSERT INTO product_identity VALUES(true,'TAXUA_LAND');
CREATE TABLE admin_users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, password_hash text NOT NULL, disabled boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE roles (code text PRIMARY KEY);
INSERT INTO roles VALUES ('DATA_VIEWER'),('DATA_EDITOR'),('VERIFIER'),('PUBLISHER'),('SYSTEM_ADMIN');
CREATE TABLE role_permissions (role_code text REFERENCES roles(code), permission text NOT NULL, PRIMARY KEY(role_code,permission));
INSERT INTO role_permissions VALUES ('DATA_VIEWER','read'),('DATA_EDITOR','read'),('DATA_EDITOR','edit'),('DATA_EDITOR','import'),('VERIFIER','read'),('VERIFIER','verify'),('PUBLISHER','read'),('PUBLISHER','publish'),('SYSTEM_ADMIN','read'),('SYSTEM_ADMIN','edit'),('SYSTEM_ADMIN','import'),('SYSTEM_ADMIN','verify'),('SYSTEM_ADMIN','publish'),('SYSTEM_ADMIN','configure');
CREATE TABLE admin_user_roles (user_id uuid REFERENCES admin_users(id), role_code text REFERENCES roles(code), PRIMARY KEY(user_id,role_code));
CREATE TABLE admin_sessions (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES admin_users(id), expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX ON admin_sessions(expires_at);
CREATE TABLE login_attempts (key_hash text PRIMARY KEY, failures integer NOT NULL DEFAULT 0, window_start timestamptz NOT NULL DEFAULT now(), blocked_until timestamptz);
CREATE TABLE audit_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_id uuid REFERENCES admin_users(id), action text NOT NULL, subject_type text NOT NULL, subject_id uuid, correlation_id uuid NOT NULL, details jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX ON audit_events(subject_type,subject_id,created_at DESC);

CREATE TABLE integration_providers (id text PRIMARY KEY, type text NOT NULL CHECK(type IN ('TERRAIN','IMAGERY','STORAGE','ROADS')), enabled boolean NOT NULL DEFAULT false, credential_status text NOT NULL DEFAULT 'MISSING' CHECK(credential_status IN ('CONFIGURED','MISSING','DISABLED','UNHEALTHY')), health_status text NOT NULL DEFAULT 'UNKNOWN', last_checked_at timestamptz, timeout_ms integer NOT NULL DEFAULT 10000 CHECK(timeout_ms BETWEEN 100 AND 60000), kill_switch boolean NOT NULL DEFAULT false);
CREATE TABLE integration_health_checks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), provider_id text NOT NULL REFERENCES integration_providers(id), status text NOT NULL, latency_ms integer, error_category text, checked_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sources (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), provider_id text REFERENCES integration_providers(id), name text NOT NULL, category text NOT NULL, authority_level source_authority NOT NULL DEFAULT 'UNKNOWN', license_name text, license_reference text, commercial_use permission_status NOT NULL DEFAULT 'UNKNOWN', public_display permission_status NOT NULL DEFAULT 'UNKNOWN', caching permission_status NOT NULL DEFAULT 'UNKNOWN', derivatives permission_status NOT NULL DEFAULT 'UNKNOWN', redistribution permission_status NOT NULL DEFAULT 'UNKNOWN', legal_reviewed_at timestamptz, source_crs text NOT NULL DEFAULT 'UNKNOWN', freshness_class text NOT NULL DEFAULT 'UNKNOWN', status text NOT NULL DEFAULT 'REVIEW_REQUIRED', last_checked_at timestamptz, notes text NOT NULL DEFAULT '', archived_at timestamptz);
CREATE TABLE import_batches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_id uuid NOT NULL REFERENCES sources(id), file_name text NOT NULL, file_hash text NOT NULL CHECK(file_hash ~ '^[a-f0-9]{64}$'), storage_key text, uploaded_by uuid NOT NULL REFERENCES admin_users(id), uploaded_at timestamptz NOT NULL DEFAULT now(), status import_status NOT NULL DEFAULT 'UPLOADED', total_rows integer NOT NULL DEFAULT 0, valid_rows integer NOT NULL DEFAULT 0, warning_rows integer NOT NULL DEFAULT 0, invalid_rows integer NOT NULL DEFAULT 0, sheet_name text, column_mapping jsonb, validation_duration_ms integer, committed_at timestamptz, expires_at timestamptz NOT NULL DEFAULT now()+interval '7 days', version integer NOT NULL DEFAULT 1);
CREATE TABLE source_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_id uuid NOT NULL REFERENCES sources(id), external_record_id text, import_batch_id uuid REFERENCES import_batches(id), collected_at timestamptz, imported_at timestamptz NOT NULL DEFAULT now(), raw_payload_hash text NOT NULL CHECK(raw_payload_hash ~ '^[a-f0-9]{64}$'), notes text NOT NULL DEFAULT '', archived_at timestamptz);
CREATE INDEX ON source_records(import_batch_id);

CREATE TABLE areas_of_interest (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, version text NOT NULL UNIQUE, source text NOT NULL, boundary geometry(Polygon,4326) NOT NULL, outside_policy text NOT NULL CHECK(outside_policy IN ('WARNING','INVALID')), active boolean NOT NULL DEFAULT false, updated_at timestamptz NOT NULL DEFAULT now(), CHECK(ST_IsValid(boundary)), CHECK(NOT ST_IsEmpty(boundary)));
CREATE INDEX ON areas_of_interest USING gist(boundary);
CREATE UNIQUE INDEX one_active_aoi ON areas_of_interest(active) WHERE active;

CREATE TABLE places (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL CHECK(length(name) BETWEEN 1 AND 200), slug text NOT NULL UNIQUE CHECK(slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'), short_description text NOT NULL DEFAULT '', description text NOT NULL DEFAULT '', area_name text NOT NULL DEFAULT '', publication_status publication_status NOT NULL DEFAULT 'DRAFT', source_record_id uuid REFERENCES source_records(id), internal_notes text NOT NULL DEFAULT '', review_required boolean NOT NULL DEFAULT true, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL REFERENCES admin_users(id), updated_by uuid NOT NULL REFERENCES admin_users(id));
CREATE INDEX ON places USING gin(name gin_trgm_ops);
CREATE INDEX ON places(publication_status,updated_at DESC);
CREATE TABLE place_geometries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), place_id uuid NOT NULL REFERENCES places(id), geometry geometry(Point,4326) NOT NULL, geometry_type text NOT NULL DEFAULT 'POINT' CHECK(geometry_type='POINT'), source_record_id uuid NOT NULL REFERENCES source_records(id), source_crs text NOT NULL, location_role location_role NOT NULL DEFAULT 'DECLARED', verification_status verification_status NOT NULL DEFAULT 'UNKNOWN', horizontal_accuracy_m double precision CHECK(horizontal_accuracy_m >= 0 AND horizontal_accuracy_m < 'Infinity'::float), observed_at timestamptz, verified_at timestamptz, verified_by uuid REFERENCES admin_users(id), verification_method text, evidence_source_record_id uuid REFERENCES source_records(id), freshness_policy text NOT NULL DEFAULT 'UNKNOWN' CHECK(freshness_policy IN ('UNKNOWN','NO_EXPIRY','EXPIRES')), expires_at timestamptz, valid_from timestamptz NOT NULL DEFAULT now(), valid_to timestamptz, created_at timestamptz NOT NULL DEFAULT now(), CHECK(NOT ST_IsEmpty(geometry)), CHECK(ST_X(geometry) BETWEEN -180 AND 180 AND ST_Y(geometry) BETWEEN -90 AND 90), CHECK(valid_to IS NULL OR valid_to >= valid_from), CHECK(expires_at IS NULL OR verified_at IS NULL OR expires_at > verified_at), CHECK(freshness_policy <> 'EXPIRES' OR expires_at IS NOT NULL), CHECK(verification_status <> 'VERIFIED' OR (verified_at IS NOT NULL AND verified_by IS NOT NULL AND length(trim(verification_method)) > 0 AND evidence_source_record_id IS NOT NULL AND freshness_policy <> 'UNKNOWN')), CHECK(location_role <> 'VERIFIED' OR verification_status IN ('VERIFIED','EXPIRED')));
CREATE INDEX ON place_geometries USING gist(geometry);
CREATE UNIQUE INDEX one_current_geometry ON place_geometries(place_id) WHERE valid_to IS NULL;
CREATE INDEX ON place_geometries(place_id,valid_from DESC);
CREATE TABLE place_categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL UNIQUE, name text NOT NULL, color text NOT NULL DEFAULT '#57c5d9' CHECK(color ~ '^#[a-fA-F0-9]{6}$'), archived_at timestamptz);
CREATE TABLE place_category_links (place_id uuid REFERENCES places(id), category_id uuid REFERENCES place_categories(id), PRIMARY KEY(place_id,category_id));
CREATE TABLE place_visit_contexts (place_id uuid PRIMARY KEY REFERENCES places(id), best_season_text text NOT NULL DEFAULT '', recommended_time_text text NOT NULL DEFAULT '', difficulty text NOT NULL DEFAULT '', audience_text text NOT NULL DEFAULT '', guide_requirement text NOT NULL DEFAULT '');
CREATE TABLE place_access_contexts (place_id uuid PRIMARY KEY REFERENCES places(id), access_method_text text NOT NULL DEFAULT '', road_condition_text text NOT NULL DEFAULT '', route_note text NOT NULL DEFAULT '', source_record_id uuid NOT NULL REFERENCES source_records(id), verification_status verification_status NOT NULL DEFAULT 'UNKNOWN', observed_at timestamptz, CHECK(verification_status <> 'VERIFIED'));
CREATE TABLE place_safety_notes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), place_id uuid NOT NULL REFERENCES places(id), note text NOT NULL, source_record_id uuid NOT NULL REFERENCES source_records(id), verification_status verification_status NOT NULL DEFAULT 'UNKNOWN', observed_at timestamptz, expires_at timestamptz, CHECK(verification_status <> 'VERIFIED'));
CREATE TABLE place_media (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), place_id uuid NOT NULL REFERENCES places(id), media_type text NOT NULL CHECK(media_type IN ('IMAGE','VIDEO_LINK','PANORAMA_360','DRONE_IMAGE')), source_url text NOT NULL CHECK(source_url LIKE 'https://%'), storage_key text, title text, alt_text text NOT NULL DEFAULT '', sort_order integer NOT NULL DEFAULT 0, source_record_id uuid NOT NULL REFERENCES source_records(id), captured_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX ON place_media(place_id,sort_order);
CREATE TABLE external_references (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subject_type text NOT NULL DEFAULT 'PLACE' CHECK(subject_type='PLACE'), subject_id uuid NOT NULL REFERENCES places(id), provider text NOT NULL, external_url text NOT NULL CHECK(external_url LIKE 'https://%'), external_id text, source_record_id uuid NOT NULL REFERENCES source_records(id));
CREATE INDEX ON external_references(external_url);

CREATE TABLE import_rows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), batch_id uuid NOT NULL REFERENCES import_batches(id), row_number integer NOT NULL, raw_data_json jsonb NOT NULL, raw_payload_hash text NOT NULL, normalized_data_json jsonb NOT NULL, validation_state text NOT NULL CHECK(validation_state IN ('VALID','WARNING','INVALID')), target_place_id uuid REFERENCES places(id), duplicate_candidate_ids uuid[] NOT NULL DEFAULT '{}', admin_action text NOT NULL DEFAULT 'REVIEW_LATER' CHECK(admin_action IN ('CREATE','UPDATE','SKIP','REVIEW_LATER')), warnings_acknowledged boolean NOT NULL DEFAULT false, reviewed_by uuid REFERENCES admin_users(id), reviewed_at timestamptz, committed_at timestamptz, UNIQUE(batch_id,row_number));
CREATE TABLE import_row_errors (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), import_row_id uuid NOT NULL REFERENCES import_rows(id), field text NOT NULL, code text NOT NULL, severity text NOT NULL CHECK(severity IN ('WARNING','INVALID')), message text NOT NULL, metadata_json jsonb NOT NULL DEFAULT '{}');
CREATE TABLE import_row_actions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), import_row_id uuid NOT NULL REFERENCES import_rows(id), actor_id uuid NOT NULL REFERENCES admin_users(id), action text NOT NULL, target_place_id uuid REFERENCES places(id), created_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE datasets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code text NOT NULL UNIQUE, name text NOT NULL, kind text NOT NULL CHECK(kind IN ('TERRAIN','IMAGERY','ROADS','PLACES')), source_id uuid NOT NULL REFERENCES sources(id));
CREATE TABLE dataset_releases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dataset_id uuid NOT NULL REFERENCES datasets(id), version text NOT NULL, source_version text NOT NULL, pipeline_version text NOT NULL, source_crs text NOT NULL, target_crs text NOT NULL, vertical_datum text NOT NULL DEFAULT 'UNKNOWN', bbox geometry(Polygon,4326), resolution double precision CHECK(resolution > 0), license text NOT NULL DEFAULT 'UNKNOWN', checksum text NOT NULL CHECK(checksum ~ '^[a-f0-9]{64}$'), qa_status release_status NOT NULL DEFAULT 'DRAFT', generated_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz, supersedes_release_id uuid REFERENCES dataset_releases(id), UNIQUE(dataset_id,version));
CREATE UNIQUE INDEX one_published_dataset_release ON dataset_releases(dataset_id) WHERE qa_status='PUBLISHED';
CREATE TABLE dataset_assets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), release_id uuid NOT NULL REFERENCES dataset_releases(id), zone text NOT NULL CHECK(zone IN ('raw','normalized','derived','published')), object_key text NOT NULL UNIQUE, checksum text NOT NULL CHECK(checksum ~ '^[a-f0-9]{64}$'), byte_size bigint NOT NULL CHECK(byte_size >= 0), content_type text NOT NULL, public_url text, CHECK(public_url IS NULL OR zone='published'));
CREATE TABLE pipeline_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dataset_id uuid NOT NULL REFERENCES datasets(id), release_id uuid REFERENCES dataset_releases(id), processing_version text NOT NULL, status text NOT NULL, started_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz, error_category text, manifest jsonb NOT NULL DEFAULT '{}');
CREATE TABLE road_segments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), release_id uuid NOT NULL REFERENCES dataset_releases(id), source_record_id uuid NOT NULL REFERENCES source_records(id), geometry geometry(LineString,4326) NOT NULL, external_id text, name text, verification_status verification_status NOT NULL DEFAULT 'UNKNOWN', CHECK(ST_IsValid(geometry)), CHECK(NOT ST_IsEmpty(geometry)));
CREATE INDEX ON road_segments USING gist(geometry);

CREATE FUNCTION protect_geometry_history() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Geometry history cannot be deleted'; END IF;
  IF OLD.valid_to IS NOT NULL OR (to_jsonb(NEW)-'valid_to') IS DISTINCT FROM (to_jsonb(OLD)-'valid_to') OR NEW.valid_to IS NULL THEN RAISE EXCEPTION 'Only closing a current validity interval is allowed'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER geometry_history BEFORE UPDATE OR DELETE ON place_geometries FOR EACH ROW EXECUTE FUNCTION protect_geometry_history();
CREATE FUNCTION protect_audit_history() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Audit events are immutable'; END $$;
CREATE TRIGGER audit_immutable BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION protect_audit_history();

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC;
